-- Segment Studio 1.0 initial schema.
-- Generated from the verified pre-release schema after removing development-only
-- workspace tables and private operator migration receipts.
CREATE TABLE segment_studio_analysis_candidates (
    id bigint NOT NULL,
    run_id uuid NOT NULL,
    video_id integer NOT NULL,
    candidate_key text NOT NULL,
    kind character varying(64) NOT NULL,
    tag_name text NOT NULL,
    title text NOT NULL,
    start_sec double precision NOT NULL,
    end_sec double precision NOT NULL,
    confidence double precision,
    model_key text NOT NULL,
    observation_count integer NOT NULL,
    review_state character varying(32) DEFAULT 'unreviewed'::character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    item_id bigint,
    CONSTRAINT "CK_segment_studio_analysis_candidates_confidence" CHECK (((confidence IS NULL) OR ((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)))),
    CONSTRAINT "CK_segment_studio_analysis_candidates_range" CHECK (((start_sec >= (0)::double precision) AND (end_sec > start_sec))),
    CONSTRAINT "CK_segment_studio_analysis_candidates_review_state" CHECK (((review_state)::text = ANY ((ARRAY['unreviewed'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])))
);


--
-- Name: segment_studio_analysis_candidates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_analysis_candidates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_analysis_candidates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_analysis_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_analysis_runs (
    id uuid NOT NULL,
    video_id integer NOT NULL,
    video_file_id integer NOT NULL,
    status character varying(32) NOT NULL,
    analyses jsonb NOT NULL,
    job_id character varying(100),
    service_run_id uuid,
    source_fingerprint text,
    result jsonb,
    error_code character varying(100),
    error_message text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT "CK_segment_studio_analysis_runs_status" CHECK (((status)::text = ANY ((ARRAY['queued'::character varying, 'running'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying])::text[])))
);


--
-- Name: segment_studio_blob_cleanup_outbox; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_blob_cleanup_outbox (
    id bigint NOT NULL,
    blob_id text NOT NULL,
    status character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    last_error text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_blob_cleanup_attempt_count" CHECK ((attempt_count >= 0)),
    CONSTRAINT "CK_segment_studio_blob_cleanup_status" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying])::text[])))
);


--
-- Name: segment_studio_blob_cleanup_outbox_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_blob_cleanup_outbox ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_blob_cleanup_outbox_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_derivation_edges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_derivation_edges (
    id bigint NOT NULL,
    source_node_id uuid NOT NULL,
    derived_node_id uuid NOT NULL,
    rule_id uuid NOT NULL,
    source_tag_id_at_creation integer CONSTRAINT segment_studio_derivation_ed_source_tag_id_at_creation_not_null NOT NULL,
    derived_tag_id_at_creation integer CONSTRAINT segment_studio_derivation_e_derived_tag_id_at_creation_not_null NOT NULL,
    activity_id uuid,
    recorded_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rule_version_at_creation text CONSTRAINT segment_studio_derivation_edg_rule_version_at_creation_not_null NOT NULL,
    CONSTRAINT "CK_segment_studio_derivation_edges_distinct_nodes" CHECK ((source_node_id <> derived_node_id))
);


--
-- Name: segment_studio_derivation_edges_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_derivation_edges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_derivation_edges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_derivation_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_derivation_rules (
    id uuid NOT NULL,
    key text NOT NULL,
    version text NOT NULL,
    source_tag_id integer NOT NULL,
    derived_tag_id integer NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_derivation_rules_distinct_tags" CHECK ((source_tag_id <> derived_tag_id))
);


--
-- Name: segment_studio_history_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_history_actions (
    id bigint NOT NULL,
    session_id bigint NOT NULL,
    sequence bigint NOT NULL,
    kind character varying(64) NOT NULL,
    label character varying(256) NOT NULL,
    before_state jsonb NOT NULL,
    after_state jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    receipt_id uuid,
    CONSTRAINT "CK_segment_studio_history_actions_kind" CHECK ((btrim((kind)::text) <> ''::text)),
    CONSTRAINT "CK_segment_studio_history_actions_label" CHECK ((btrim((label)::text) <> ''::text)),
    CONSTRAINT "CK_segment_studio_history_actions_sequence" CHECK ((sequence > 0))
);


--
-- Name: segment_studio_history_actions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_history_actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_history_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_history_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_history_sessions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    video_id integer NOT NULL,
    cursor_sequence bigint DEFAULT 0 NOT NULL,
    revision bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    mode character varying(16) DEFAULT 'full'::character varying NOT NULL,
    CONSTRAINT "CK_segment_studio_history_sessions_cursor" CHECK ((cursor_sequence >= 0)),
    CONSTRAINT "CK_segment_studio_history_sessions_mode" CHECK (((mode)::text = ANY ((ARRAY['basic'::character varying, 'full'::character varying])::text[]))),
    CONSTRAINT "CK_segment_studio_history_sessions_revision" CHECK ((revision >= 0))
);


--
-- Name: segment_studio_history_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_history_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_history_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_incorrect_examples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_incorrect_examples (
    id bigint NOT NULL,
    item_id bigint,
    video_id integer NOT NULL,
    snapshot jsonb NOT NULL,
    created_by_user_id integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    native_bin_entry_id bigint,
    revision bigint DEFAULT 1 NOT NULL,
    CONSTRAINT "CK_segment_studio_incorrect_examples_representation" CHECK ((num_nonnulls(item_id, native_bin_entry_id) = 1))
);


--
-- Name: segment_studio_incorrect_examples_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_incorrect_examples ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_incorrect_examples_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_installation_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_installation_state (
    id smallint NOT NULL,
    requires_legacy_normalization boolean CONSTRAINT segment_studio_installation_requires_legacy_normalizat_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    lineage_rollout_paused boolean DEFAULT false CONSTRAINT segment_studio_installation_sta_lineage_rollout_paused_not_null NOT NULL,
    CONSTRAINT "CK_segment_studio_installation_state_singleton" CHECK ((id = 1))
);


--
-- Name: segment_studio_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_items (
    id bigint NOT NULL,
    native_segment_id integer,
    review_state character varying(32),
    representation_schema_version integer DEFAULT 1 NOT NULL,
    video_id integer,
    start_sec double precision,
    end_sec double precision,
    tag_id integer,
    kind text,
    ref_id bigint,
    payload jsonb,
    source_key text,
    source_run_id text,
    confidence real,
    title text,
    color_hint text,
    extension_image_blob_id text,
    revision bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_items_representation" CHECK ((((native_segment_id IS NOT NULL) AND (review_state IS NULL) AND (video_id IS NULL) AND (start_sec IS NULL) AND (end_sec IS NULL) AND (tag_id IS NULL) AND (kind IS NULL) AND (ref_id IS NULL) AND (payload IS NULL) AND (source_key IS NULL) AND (source_run_id IS NULL) AND (confidence IS NULL) AND (title IS NULL) AND (color_hint IS NULL) AND (extension_image_blob_id IS NULL)) OR ((native_segment_id IS NULL) AND ((review_state)::text = ANY ((ARRAY['unreviewed'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])) AND (video_id IS NOT NULL) AND (start_sec IS NOT NULL) AND (tag_id IS NOT NULL) AND (kind IS NOT NULL) AND (source_key IS NOT NULL)))),
    CONSTRAINT "CK_segment_studio_items_revision" CHECK ((revision >= 0)),
    CONSTRAINT "CK_segment_studio_items_schema_version" CHECK ((representation_schema_version > 0))
);


--
-- Name: segment_studio_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_lineage_issues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_lineage_issues (
    id uuid NOT NULL,
    issue_fingerprint text NOT NULL,
    component_key text NOT NULL,
    issue_kind character varying(64) NOT NULL,
    state character varying(16) NOT NULL,
    lineage_node_id uuid,
    edge_id bigint,
    details jsonb NOT NULL,
    first_detected_at timestamp with time zone NOT NULL,
    last_detected_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    resolution jsonb,
    CONSTRAINT "CK_segment_studio_lineage_issues_kind" CHECK (((issue_kind)::text = ANY ((ARRAY['missing-item'::character varying, 'missing-source'::character varying, 'missing-derived'::character varying, 'derived-tag-mismatch'::character varying, 'source-tag-mismatch'::character varying, 'rule-missing'::character varying, 'rule-version-missing'::character varying, 'rule-no-longer-matches'::character varying, 'cycle'::character varying, 'cross-video-edge'::character varying, 'partial-component-deletion'::character varying, 'provenance-mismatch'::character varying, 'missing-endpoint'::character varying, 'root-tag-mismatch'::character varying, 'missing-rule'::character varying, 'missing-rule-version'::character varying, 'rule-tag-mismatch'::character varying])::text[]))),
    CONSTRAINT "CK_segment_studio_lineage_issues_resolved" CHECK ((((state)::text <> 'resolved'::text) OR (resolved_at IS NOT NULL))),
    CONSTRAINT "CK_segment_studio_lineage_issues_state" CHECK (((state)::text = ANY ((ARRAY['open'::character varying, 'resolved'::character varying, 'ignored'::character varying])::text[])))
);


--
-- Name: segment_studio_lineage_nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_lineage_nodes (
    id uuid NOT NULL,
    item_id bigint,
    state character varying(16) NOT NULL,
    last_known_video_id integer NOT NULL,
    last_known_tag_id integer,
    last_known_start_sec double precision,
    last_known_end_sec double precision,
    missing_since timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_lineage_nodes_state" CHECK (((((state)::text = 'live'::text) AND (item_id IS NOT NULL) AND (missing_since IS NULL)) OR (((state)::text = 'missing'::text) AND (item_id IS NULL) AND (missing_since IS NOT NULL))))
);


--
-- Name: segment_studio_lineage_scan_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_lineage_scan_runs (
    id uuid NOT NULL,
    scope character varying(16) NOT NULL,
    scope_key text,
    state character varying(16) NOT NULL,
    cursor jsonb,
    source_fingerprint text,
    counts jsonb DEFAULT '{}'::jsonb NOT NULL,
    requested_by_user_id integer,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_lineage_scan_runs_scope" CHECK (((scope)::text = ANY ((ARRAY['full'::character varying, 'video'::character varying, 'component'::character varying])::text[]))),
    CONSTRAINT "CK_segment_studio_lineage_scan_runs_scope_key" CHECK (((((scope)::text = 'full'::text) AND (scope_key IS NULL)) OR (((scope)::text <> 'full'::text) AND (scope_key IS NOT NULL)))),
    CONSTRAINT "CK_segment_studio_lineage_scan_runs_state" CHECK (((state)::text = ANY ((ARRAY['pending'::character varying, 'running'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying])::text[])))
);


--
-- Name: segment_studio_native_recycle_bin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_native_recycle_bin (
    id bigint NOT NULL,
    video_id integer NOT NULL,
    tag_id integer NOT NULL,
    start_sec double precision NOT NULL,
    end_sec double precision,
    kind text NOT NULL,
    ref_id bigint,
    payload jsonb,
    source_key text NOT NULL,
    source_run_id text,
    confidence real,
    title text,
    color_hint text,
    image_blob_id text,
    revision bigint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    field_provenance jsonb DEFAULT '[]'::jsonb NOT NULL,
    native_created_at timestamp with time zone NOT NULL,
    preserved_anchor jsonb,
    CONSTRAINT "CK_segment_studio_native_bin_revision" CHECK ((revision > 0))
);


--
-- Name: segment_studio_native_recycle_bin_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_native_recycle_bin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_native_recycle_bin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_provenance_activities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_provenance_activities (
    id uuid NOT NULL,
    key text NOT NULL,
    kind character varying(32) NOT NULL,
    source_id bigint NOT NULL,
    external_run_id text,
    status character varying(32),
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    request jsonb,
    models jsonb,
    summary jsonb,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_provenance_activities_kind" CHECK (((kind)::text = ANY ((ARRAY['ai-analysis'::character varying, 'migration'::character varying, 'import'::character varying, 'manual'::character varying])::text[])))
);


--
-- Name: segment_studio_review_segments; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW segment_studio_review_segments AS
 SELECT "Id" AS segment_id,
    "HostId" AS video_id,
    "TagId" AS tag_id,
        CASE
            WHEN ((("Payload" -> 'segmentStudio'::text) ->> 'reviewState'::text) = ANY (ARRAY['approved'::text, 'rejected'::text])) THEN (("Payload" -> 'segmentStudio'::text) ->> 'reviewState'::text)
            ELSE 'unreviewed'::text
        END AS review_state
   FROM segments
  WHERE (("HostType" = 1) AND ("Kind" = 'tag'::text) AND ("TagId" IS NOT NULL));


--
-- Name: segment_studio_segment_group_operations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_segment_group_operations (
    operation_id uuid NOT NULL,
    kind character varying(32) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: segment_studio_segment_group_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_segment_group_tags (
    segment_group_id bigint NOT NULL,
    tag_id integer NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT "CK_segment_studio_segment_group_tags_sort_order" CHECK ((sort_order >= 0))
);


--
-- Name: segment_studio_segment_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_segment_groups (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_segment_groups_sort_order" CHECK ((sort_order >= 0))
);


--
-- Name: segment_studio_segment_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_segment_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_segment_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_segment_operations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_segment_operations (
    operation_id uuid NOT NULL,
    kind character varying(64) NOT NULL,
    actor_user_id integer,
    request_fingerprint text NOT NULL,
    item_id bigint,
    source_native_segment_id integer,
    result_native_segment_id integer,
    result_payload jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    component_fingerprint text
);


--
-- Name: segment_studio_segment_provenance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_segment_provenance (
    id bigint NOT NULL,
    lineage_node_id uuid NOT NULL,
    source_id bigint NOT NULL,
    relation character varying(16) NOT NULL,
    activity_id uuid,
    model_key text,
    model_identifier text,
    model_version text,
    confidence real,
    recorded_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    superseded_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_segment_provenance_confidence" CHECK (((confidence IS NULL) OR ((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)))),
    CONSTRAINT "CK_segment_studio_segment_provenance_relation" CHECK (((relation)::text = ANY ((ARRAY['origin'::character varying, 'inherited'::character varying])::text[])))
);


--
-- Name: segment_studio_segment_provenance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_segment_provenance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_segment_provenance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_segment_slots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_segment_slots (
    slot_definition_id uuid NOT NULL,
    performer_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    item_id bigint NOT NULL
);


--
-- Name: segment_studio_shot_boundaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_shot_boundaries (
    id bigint NOT NULL,
    video_id integer NOT NULL,
    start_sec double precision NOT NULL,
    end_sec double precision NOT NULL,
    source character varying(32) DEFAULT 'manual'::character varying NOT NULL,
    metadata jsonb,
    revision bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_shot_boundaries_revision" CHECK ((revision >= 0)),
    CONSTRAINT "CK_segment_studio_shot_boundaries_source" CHECK (((source)::text = ANY ((ARRAY['manual'::character varying, 'pyscenedetect'::character varying, 'omnishotcut'::character varying])::text[]))),
    CONSTRAINT "CK_segment_studio_shot_boundaries_time" CHECK (((start_sec >= (0)::double precision) AND (end_sec > start_sec)))
);


--
-- Name: segment_studio_shot_boundaries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_shot_boundaries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_shot_boundaries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_shot_boundary_operations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_shot_boundary_operations (
    operation_id uuid NOT NULL,
    video_id integer NOT NULL,
    kind character varying(32) NOT NULL,
    request_fingerprint text CONSTRAINT segment_studio_shot_boundary_opera_request_fingerprint_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_shot_boundary_operations_kind" CHECK (((kind)::text = ANY ((ARRAY['split'::character varying, 'merge'::character varying, 'restore'::character varying])::text[])))
);


--
-- Name: segment_studio_slot_definition_gender_hints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_slot_definition_gender_hints (
    slot_definition_id uuid CONSTRAINT segment_studio_slot_definition_gend_slot_definition_id_not_null NOT NULL,
    gender_hint character varying(32) CONSTRAINT segment_studio_slot_definition_gender_hint_gender_hint_not_null NOT NULL,
    CONSTRAINT "CK_segment_studio_slot_definition_gender_hints_value" CHECK (((gender_hint)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'TRANSGENDER_MALE'::character varying, 'TRANSGENDER_FEMALE'::character varying])::text[])))
);


--
-- Name: segment_studio_slot_definition_sets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_slot_definition_sets (
    id uuid NOT NULL,
    tag_id integer NOT NULL,
    allow_same_performer_in_multiple_slots boolean DEFAULT false CONSTRAINT segment_studio_slot_definit_allow_same_performer_in_mu_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: segment_studio_slot_definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_slot_definitions (
    id uuid NOT NULL,
    slot_definition_set_id uuid NOT NULL,
    label text,
    sort_order integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_slot_definitions_sort_order" CHECK ((sort_order >= 0))
);


--
-- Name: segment_studio_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_sources (
    id bigint NOT NULL,
    key text NOT NULL,
    display_name text NOT NULL,
    category character varying(64),
    provider character varying(256),
    default_model_identifier character varying(256),
    description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT "CK_segment_studio_sources_key" CHECK (((key = lower(btrim(key))) AND (key <> ''::text)))
);


--
-- Name: segment_studio_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_training_export_examples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_training_export_examples (
    id bigint NOT NULL,
    export_id uuid NOT NULL,
    "position" integer NOT NULL,
    captured_example_id bigint CONSTRAINT segment_studio_training_export_exa_captured_example_id_not_null NOT NULL,
    captured_example_revision bigint CONSTRAINT segment_studio_training_expo_captured_example_revision_not_null NOT NULL,
    item_id bigint,
    native_bin_entry_id bigint,
    snapshot jsonb NOT NULL,
    CONSTRAINT "CK_segment_studio_training_export_examples_position" CHECK (("position" >= 0)),
    CONSTRAINT "CK_segment_studio_training_export_examples_representation" CHECK ((num_nonnulls(item_id, native_bin_entry_id) = 1))
);


--
-- Name: segment_studio_training_export_examples_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_training_export_examples ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_training_export_examples_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_training_export_frames; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_training_export_frames (
    id bigint NOT NULL,
    export_example_id bigint CONSTRAINT segment_studio_training_export_frame_export_example_id_not_null NOT NULL,
    "position" integer NOT NULL,
    timestamp_sec double precision NOT NULL,
    image_blob_id text NOT NULL,
    CONSTRAINT "CK_segment_studio_training_export_frames_position" CHECK (("position" >= 0)),
    CONSTRAINT "CK_segment_studio_training_export_frames_timestamp" CHECK ((timestamp_sec >= (0)::double precision))
);


--
-- Name: segment_studio_training_export_frames_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE segment_studio_training_export_frames ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME segment_studio_training_export_frames_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_studio_training_export_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_training_export_items (
    export_id uuid NOT NULL,
    item_id bigint NOT NULL,
    image_blob_id text
);


--
-- Name: segment_studio_training_exports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_training_exports (
    id uuid NOT NULL,
    video_id integer NOT NULL,
    manifest jsonb NOT NULL,
    example_count integer NOT NULL,
    requested_by_user_id integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    capture_operation_id uuid,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT "CK_segment_studio_training_exports_count" CHECK ((example_count >= 0))
);


--
-- Name: segment_studio_user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE segment_studio_user_preferences (
    user_id integer NOT NULL,
    mode character varying(32) DEFAULT 'editor'::character varying NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "CK_segment_studio_user_preferences_mode" CHECK (((mode)::text = ANY ((ARRAY['editor'::character varying, 'review'::character varying])::text[])))
);


--
-- Name: segment_studio_segment_slots PK_segment_studio_segment_slots; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_slots
    ADD CONSTRAINT "PK_segment_studio_segment_slots" PRIMARY KEY (item_id, slot_definition_id);


--
-- Name: segment_studio_history_sessions UQ_segment_studio_history_sessions_user_video_mode; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_history_sessions
    ADD CONSTRAINT "UQ_segment_studio_history_sessions_user_video_mode" UNIQUE (user_id, video_id, mode);


--
-- Name: segment_studio_analysis_candidates segment_studio_analysis_candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_analysis_candidates
    ADD CONSTRAINT segment_studio_analysis_candidates_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_analysis_runs segment_studio_analysis_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_analysis_runs
    ADD CONSTRAINT segment_studio_analysis_runs_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_blob_cleanup_outbox segment_studio_blob_cleanup_outbox_blob_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_blob_cleanup_outbox
    ADD CONSTRAINT segment_studio_blob_cleanup_outbox_blob_id_key UNIQUE (blob_id);


--
-- Name: segment_studio_blob_cleanup_outbox segment_studio_blob_cleanup_outbox_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_blob_cleanup_outbox
    ADD CONSTRAINT segment_studio_blob_cleanup_outbox_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_derivation_edges segment_studio_derivation_edg_source_node_id_derived_node_i_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_edges
    ADD CONSTRAINT segment_studio_derivation_edg_source_node_id_derived_node_i_key UNIQUE (source_node_id, derived_node_id, rule_id);


--
-- Name: segment_studio_derivation_edges segment_studio_derivation_edges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_edges
    ADD CONSTRAINT segment_studio_derivation_edges_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_derivation_rules segment_studio_derivation_rul_key_version_source_tag_id_der_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_rules
    ADD CONSTRAINT segment_studio_derivation_rul_key_version_source_tag_id_der_key UNIQUE (key, version, source_tag_id, derived_tag_id);


--
-- Name: segment_studio_derivation_rules segment_studio_derivation_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_rules
    ADD CONSTRAINT segment_studio_derivation_rules_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_history_actions segment_studio_history_actions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_history_actions
    ADD CONSTRAINT segment_studio_history_actions_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_history_actions segment_studio_history_actions_session_id_sequence_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_history_actions
    ADD CONSTRAINT segment_studio_history_actions_session_id_sequence_key UNIQUE (session_id, sequence);


--
-- Name: segment_studio_history_sessions segment_studio_history_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_history_sessions
    ADD CONSTRAINT segment_studio_history_sessions_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_incorrect_examples segment_studio_incorrect_examples_item_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_incorrect_examples
    ADD CONSTRAINT segment_studio_incorrect_examples_item_id_key UNIQUE (item_id);


--
-- Name: segment_studio_incorrect_examples segment_studio_incorrect_examples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_incorrect_examples
    ADD CONSTRAINT segment_studio_incorrect_examples_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_installation_state segment_studio_installation_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_installation_state
    ADD CONSTRAINT segment_studio_installation_state_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_items segment_studio_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_items
    ADD CONSTRAINT segment_studio_items_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_lineage_issues segment_studio_lineage_issues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_lineage_issues
    ADD CONSTRAINT segment_studio_lineage_issues_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_lineage_nodes segment_studio_lineage_nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_lineage_nodes
    ADD CONSTRAINT segment_studio_lineage_nodes_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_lineage_scan_runs segment_studio_lineage_scan_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_lineage_scan_runs
    ADD CONSTRAINT segment_studio_lineage_scan_runs_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_native_recycle_bin segment_studio_native_recycle_bin_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_native_recycle_bin
    ADD CONSTRAINT segment_studio_native_recycle_bin_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_provenance_activities segment_studio_provenance_activities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_provenance_activities
    ADD CONSTRAINT segment_studio_provenance_activities_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_segment_group_operations segment_studio_segment_group_operations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_group_operations
    ADD CONSTRAINT segment_studio_segment_group_operations_pkey PRIMARY KEY (operation_id);


--
-- Name: segment_studio_segment_group_tags segment_studio_segment_group_ta_segment_group_id_sort_order_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_group_tags
    ADD CONSTRAINT segment_studio_segment_group_ta_segment_group_id_sort_order_key UNIQUE (segment_group_id, sort_order);


--
-- Name: segment_studio_segment_group_tags segment_studio_segment_group_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_group_tags
    ADD CONSTRAINT segment_studio_segment_group_tags_pkey PRIMARY KEY (segment_group_id, tag_id);


--
-- Name: segment_studio_segment_group_tags segment_studio_segment_group_tags_tag_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_group_tags
    ADD CONSTRAINT segment_studio_segment_group_tags_tag_id_key UNIQUE (tag_id);


--
-- Name: segment_studio_segment_groups segment_studio_segment_groups_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_groups
    ADD CONSTRAINT segment_studio_segment_groups_name_key UNIQUE (name);


--
-- Name: segment_studio_segment_groups segment_studio_segment_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_groups
    ADD CONSTRAINT segment_studio_segment_groups_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_segment_groups segment_studio_segment_groups_sort_order_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_groups
    ADD CONSTRAINT segment_studio_segment_groups_sort_order_key UNIQUE (sort_order);


--
-- Name: segment_studio_segment_operations segment_studio_segment_operations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_operations
    ADD CONSTRAINT segment_studio_segment_operations_pkey PRIMARY KEY (operation_id);


--
-- Name: segment_studio_segment_provenance segment_studio_segment_provenance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_provenance
    ADD CONSTRAINT segment_studio_segment_provenance_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_shot_boundaries segment_studio_shot_boundaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_shot_boundaries
    ADD CONSTRAINT segment_studio_shot_boundaries_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_shot_boundaries segment_studio_shot_boundaries_video_id_start_sec_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_shot_boundaries
    ADD CONSTRAINT segment_studio_shot_boundaries_video_id_start_sec_key UNIQUE (video_id, start_sec);


--
-- Name: segment_studio_shot_boundary_operations segment_studio_shot_boundary_operations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_shot_boundary_operations
    ADD CONSTRAINT segment_studio_shot_boundary_operations_pkey PRIMARY KEY (operation_id);


--
-- Name: segment_studio_slot_definitions segment_studio_slot_definitio_slot_definition_set_id_sort_o_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_slot_definitions
    ADD CONSTRAINT segment_studio_slot_definitio_slot_definition_set_id_sort_o_key UNIQUE (slot_definition_set_id, sort_order);


--
-- Name: segment_studio_slot_definition_gender_hints segment_studio_slot_definition_gender_hints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_slot_definition_gender_hints
    ADD CONSTRAINT segment_studio_slot_definition_gender_hints_pkey PRIMARY KEY (slot_definition_id, gender_hint);


--
-- Name: segment_studio_slot_definition_sets segment_studio_slot_definition_sets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_slot_definition_sets
    ADD CONSTRAINT segment_studio_slot_definition_sets_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_slot_definition_sets segment_studio_slot_definition_sets_tag_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_slot_definition_sets
    ADD CONSTRAINT segment_studio_slot_definition_sets_tag_id_key UNIQUE (tag_id);


--
-- Name: segment_studio_slot_definitions segment_studio_slot_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_slot_definitions
    ADD CONSTRAINT segment_studio_slot_definitions_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_sources segment_studio_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_sources
    ADD CONSTRAINT segment_studio_sources_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_training_export_examples segment_studio_training_export_examples_export_id_position_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_export_examples
    ADD CONSTRAINT segment_studio_training_export_examples_export_id_position_key UNIQUE (export_id, "position");


--
-- Name: segment_studio_training_export_examples segment_studio_training_export_examples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_export_examples
    ADD CONSTRAINT segment_studio_training_export_examples_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_training_export_frames segment_studio_training_export_f_export_example_id_position_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_export_frames
    ADD CONSTRAINT segment_studio_training_export_f_export_example_id_position_key UNIQUE (export_example_id, "position");


--
-- Name: segment_studio_training_export_frames segment_studio_training_export_frames_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_export_frames
    ADD CONSTRAINT segment_studio_training_export_frames_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_training_export_items segment_studio_training_export_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_export_items
    ADD CONSTRAINT segment_studio_training_export_items_pkey PRIMARY KEY (export_id, item_id);


--
-- Name: segment_studio_training_exports segment_studio_training_exports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_exports
    ADD CONSTRAINT segment_studio_training_exports_pkey PRIMARY KEY (id);


--
-- Name: segment_studio_user_preferences segment_studio_user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_user_preferences
    ADD CONSTRAINT segment_studio_user_preferences_pkey PRIMARY KEY (user_id);


--
-- Name: IX_segment_studio_analysis_candidates_item_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_analysis_candidates_item_id" ON segment_studio_analysis_candidates USING btree (item_id) WHERE (item_id IS NOT NULL);


--
-- Name: IX_segment_studio_analysis_candidates_run_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_analysis_candidates_run_key" ON segment_studio_analysis_candidates USING btree (run_id, candidate_key);


--
-- Name: IX_segment_studio_analysis_candidates_video_review; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_analysis_candidates_video_review" ON segment_studio_analysis_candidates USING btree (video_id, review_state);


--
-- Name: IX_segment_studio_analysis_runs_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_analysis_runs_job_id" ON segment_studio_analysis_runs USING btree (job_id);


--
-- Name: IX_segment_studio_analysis_runs_video_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_analysis_runs_video_created" ON segment_studio_analysis_runs USING btree (video_id, created_at);


--
-- Name: IX_segment_studio_blob_cleanup_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_blob_cleanup_status_created" ON segment_studio_blob_cleanup_outbox USING btree (status, created_at);


--
-- Name: IX_segment_studio_derivation_edges_activity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_derivation_edges_activity" ON segment_studio_derivation_edges USING btree (activity_id);


--
-- Name: IX_segment_studio_derivation_edges_derived; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_derivation_edges_derived" ON segment_studio_derivation_edges USING btree (derived_node_id);


--
-- Name: IX_segment_studio_derivation_edges_rule; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_derivation_edges_rule" ON segment_studio_derivation_edges USING btree (rule_id);


--
-- Name: IX_segment_studio_derivation_edges_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_derivation_edges_source" ON segment_studio_derivation_edges USING btree (source_node_id);


--
-- Name: IX_segment_studio_derivation_rules_derived_tag; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_derivation_rules_derived_tag" ON segment_studio_derivation_rules USING btree (derived_tag_id);


--
-- Name: IX_segment_studio_derivation_rules_relationship; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_derivation_rules_relationship" ON segment_studio_derivation_rules USING btree (source_tag_id, derived_tag_id);


--
-- Name: IX_segment_studio_derivation_rules_source_tag; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_derivation_rules_source_tag" ON segment_studio_derivation_rules USING btree (source_tag_id);


--
-- Name: IX_segment_studio_history_actions_receipt_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_history_actions_receipt_id" ON segment_studio_history_actions USING btree (receipt_id) WHERE (receipt_id IS NOT NULL);


--
-- Name: IX_segment_studio_history_actions_session_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_history_actions_session_created" ON segment_studio_history_actions USING btree (session_id, created_at, id);


--
-- Name: IX_segment_studio_incorrect_examples_native_bin; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_incorrect_examples_native_bin" ON segment_studio_incorrect_examples USING btree (native_bin_entry_id) WHERE (native_bin_entry_id IS NOT NULL);


--
-- Name: IX_segment_studio_incorrect_examples_video_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_incorrect_examples_video_created" ON segment_studio_incorrect_examples USING btree (video_id, created_at, id);


--
-- Name: IX_segment_studio_items_native_segment; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_items_native_segment" ON segment_studio_items USING btree (native_segment_id);


--
-- Name: IX_segment_studio_items_owned_blob; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_items_owned_blob" ON segment_studio_items USING btree (extension_image_blob_id) WHERE (extension_image_blob_id IS NOT NULL);


--
-- Name: IX_segment_studio_items_owned_tag_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_items_owned_tag_state" ON segment_studio_items USING btree (tag_id, review_state, video_id, start_sec, id) WHERE (native_segment_id IS NULL);


--
-- Name: IX_segment_studio_items_owned_video_state_start; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_items_owned_video_state_start" ON segment_studio_items USING btree (video_id, review_state, start_sec, id) WHERE (native_segment_id IS NULL);


--
-- Name: IX_segment_studio_lineage_issues_active_fingerprint; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_lineage_issues_active_fingerprint" ON segment_studio_lineage_issues USING btree (issue_fingerprint) WHERE ((state)::text = 'open'::text);


--
-- Name: IX_segment_studio_lineage_issues_component; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_lineage_issues_component" ON segment_studio_lineage_issues USING btree (component_key);


--
-- Name: IX_segment_studio_lineage_issues_edge; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_lineage_issues_edge" ON segment_studio_lineage_issues USING btree (edge_id);


--
-- Name: IX_segment_studio_lineage_issues_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_lineage_issues_kind" ON segment_studio_lineage_issues USING btree (issue_kind);


--
-- Name: IX_segment_studio_lineage_issues_node; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_lineage_issues_node" ON segment_studio_lineage_issues USING btree (lineage_node_id);


--
-- Name: IX_segment_studio_lineage_issues_open_detected; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_lineage_issues_open_detected" ON segment_studio_lineage_issues USING btree (last_detected_at DESC, id) WHERE ((state)::text = 'open'::text);


--
-- Name: IX_segment_studio_lineage_issues_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_lineage_issues_state" ON segment_studio_lineage_issues USING btree (state);


--
-- Name: IX_segment_studio_lineage_nodes_item_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_lineage_nodes_item_id" ON segment_studio_lineage_nodes USING btree (item_id) WHERE (item_id IS NOT NULL);


--
-- Name: IX_segment_studio_lineage_nodes_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_lineage_nodes_state" ON segment_studio_lineage_nodes USING btree (state);


--
-- Name: IX_segment_studio_lineage_nodes_tag; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_lineage_nodes_tag" ON segment_studio_lineage_nodes USING btree (last_known_tag_id);


--
-- Name: IX_segment_studio_lineage_nodes_video; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_lineage_nodes_video" ON segment_studio_lineage_nodes USING btree (last_known_video_id);


--
-- Name: IX_segment_studio_lineage_scan_runs_active_full; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_lineage_scan_runs_active_full" ON segment_studio_lineage_scan_runs USING btree (scope) WHERE (((scope)::text = 'full'::text) AND ((state)::text = ANY ((ARRAY['pending'::character varying, 'running'::character varying])::text[])));


--
-- Name: IX_segment_studio_native_bin_blob; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_native_bin_blob" ON segment_studio_native_recycle_bin USING btree (image_blob_id) WHERE (image_blob_id IS NOT NULL);


--
-- Name: IX_segment_studio_native_bin_video_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_native_bin_video_updated" ON segment_studio_native_recycle_bin USING btree (video_id, updated_at, id);


--
-- Name: IX_segment_studio_provenance_activities_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_provenance_activities_key" ON segment_studio_provenance_activities USING btree (key);


--
-- Name: IX_segment_studio_provenance_activities_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_provenance_activities_kind" ON segment_studio_provenance_activities USING btree (kind);


--
-- Name: IX_segment_studio_provenance_activities_source_external_run; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_provenance_activities_source_external_run" ON segment_studio_provenance_activities USING btree (source_id, external_run_id) WHERE (external_run_id IS NOT NULL);


--
-- Name: IX_segment_studio_segment_group_operations_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_group_operations_created" ON segment_studio_segment_group_operations USING btree (created_at);


--
-- Name: IX_segment_studio_segment_group_tags_group; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_group_tags_group" ON segment_studio_segment_group_tags USING btree (segment_group_id, sort_order);


--
-- Name: IX_segment_studio_segment_operations_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_operations_created" ON segment_studio_segment_operations USING btree (created_at);


--
-- Name: IX_segment_studio_segment_provenance_active_identity; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_segment_provenance_active_identity" ON segment_studio_segment_provenance USING btree (lineage_node_id, source_id, relation, activity_id, model_key, model_identifier, model_version) NULLS NOT DISTINCT WHERE (superseded_at IS NULL);


--
-- Name: IX_segment_studio_segment_provenance_active_node_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_provenance_active_node_source" ON segment_studio_segment_provenance USING btree (lineage_node_id, source_id) WHERE (superseded_at IS NULL);


--
-- Name: IX_segment_studio_segment_provenance_activity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_provenance_activity" ON segment_studio_segment_provenance USING btree (activity_id);


--
-- Name: IX_segment_studio_segment_provenance_model; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_provenance_model" ON segment_studio_segment_provenance USING btree (model_identifier);


--
-- Name: IX_segment_studio_segment_provenance_node; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_provenance_node" ON segment_studio_segment_provenance USING btree (lineage_node_id);


--
-- Name: IX_segment_studio_segment_provenance_recorded; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_provenance_recorded" ON segment_studio_segment_provenance USING btree (recorded_at);


--
-- Name: IX_segment_studio_segment_provenance_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_provenance_source" ON segment_studio_segment_provenance USING btree (source_id);


--
-- Name: IX_segment_studio_segment_slots_definition; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_slots_definition" ON segment_studio_segment_slots USING btree (slot_definition_id, item_id);


--
-- Name: IX_segment_studio_segment_slots_definition_performer_item; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_slots_definition_performer_item" ON segment_studio_segment_slots USING btree (slot_definition_id, performer_id, item_id);


--
-- Name: IX_segment_studio_segment_slots_performer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_segment_slots_performer" ON segment_studio_segment_slots USING btree (performer_id, item_id);


--
-- Name: IX_segment_studio_shot_boundaries_video_end; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_shot_boundaries_video_end" ON segment_studio_shot_boundaries USING btree (video_id, end_sec, id);


--
-- Name: IX_segment_studio_shot_boundary_operations_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_shot_boundary_operations_created" ON segment_studio_shot_boundary_operations USING btree (created_at);


--
-- Name: IX_segment_studio_sources_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_sources_category" ON segment_studio_sources USING btree (category);


--
-- Name: IX_segment_studio_sources_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_sources_key" ON segment_studio_sources USING btree (key);


--
-- Name: IX_segment_studio_training_export_examples_working; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_training_export_examples_working" ON segment_studio_training_export_examples USING btree (captured_example_id);


--
-- Name: IX_segment_studio_training_export_items_item; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_training_export_items_item" ON segment_studio_training_export_items USING btree (item_id, export_id);


--
-- Name: IX_segment_studio_training_exports_capture_operation; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_segment_studio_training_exports_capture_operation" ON segment_studio_training_exports USING btree (capture_operation_id) WHERE (capture_operation_id IS NOT NULL);


--
-- Name: IX_segment_studio_training_exports_video_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_segment_studio_training_exports_video_created" ON segment_studio_training_exports USING btree (video_id, created_at, id);


--
-- Name: segment_studio_derivation_rules segment_studio_derivation_rules_delete_derivations; Type: TRIGGER; Schema: public; Owner: -
--


-- Indexes contributed to Cove core tables.
CREATE INDEX "IX_segment_studio_ai_segments_ingestion" ON segments USING btree ("Id") WHERE (("HostType" = 1) AND ("Kind" = 'tag'::text) AND ("TagId" IS NOT NULL) AND ("SourceKey" ~~ 'ext:ai.%'::text));
CREATE INDEX "IX_segment_studio_browse_activity_state" ON segments USING btree ("TagId", COALESCE((("Payload" -> 'segmentStudio'::text) ->> 'reviewState'::text), 'unreviewed'::text), "HostId", "StartSec", "Id") WHERE (("HostType" = 1) AND ("Kind" = 'tag'::text) AND ("TagId" IS NOT NULL));
CREATE INDEX "IX_segment_studio_review_segments_video_state_tag" ON segments USING btree ("HostId", (
CASE
    WHEN ((("Payload" -> 'segmentStudio'::text) ->> 'reviewState'::text) = ANY (ARRAY['approved'::text, 'rejected'::text])) THEN (("Payload" -> 'segmentStudio'::text) ->> 'reviewState'::text)
    ELSE 'unreviewed'::text
END), "TagId") WHERE (("HostType" = 1) AND ("Kind" = 'tag'::text) AND ("TagId" IS NOT NULL));

-- Trigger functions.
CREATE OR REPLACE FUNCTION segment_studio_delete_rule_derivations()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    removed_edge_ids BIGINT[] := ARRAY[]::BIGINT[];
    deleted_node_ids UUID[] := ARRAY[]::UUID[];
    added_edge_ids BIGINT[];
    added_node_ids UUID[];
    deleted_item_ids BIGINT[];
    deleted_native_segment_ids INTEGER[];
    deleted_video_ids INTEGER[];
BEGIN
    removed_edge_ids := ARRAY(
        SELECT edge.id
        FROM segment_studio_derivation_edges AS edge
        WHERE edge.rule_id = OLD.id
    );

    LOOP
        added_node_ids := ARRAY(
            SELECT DISTINCT removed.derived_node_id
            FROM segment_studio_derivation_edges AS removed
            WHERE removed.id = ANY(removed_edge_ids)
              AND removed.derived_node_id <> ALL(deleted_node_ids)
              AND NOT EXISTS (
                  SELECT 1
                  FROM segment_studio_derivation_edges AS incoming
                  WHERE incoming.derived_node_id = removed.derived_node_id
                    AND incoming.id <> ALL(removed_edge_ids)
              )
        );
        deleted_node_ids := deleted_node_ids || added_node_ids;

        added_edge_ids := ARRAY(
            SELECT outgoing.id
            FROM segment_studio_derivation_edges AS outgoing
            WHERE outgoing.source_node_id = ANY(deleted_node_ids)
              AND outgoing.id <> ALL(removed_edge_ids)
        );
        removed_edge_ids := removed_edge_ids || added_edge_ids;

        EXIT WHEN cardinality(added_node_ids) = 0
            AND cardinality(added_edge_ids) = 0;
    END LOOP;

    deleted_item_ids := ARRAY(
        SELECT node.item_id
        FROM segment_studio_lineage_nodes AS node
        WHERE node.id = ANY(deleted_node_ids)
          AND node.item_id IS NOT NULL
    );
    deleted_native_segment_ids := ARRAY(
        SELECT item.native_segment_id
        FROM segment_studio_items AS item
        WHERE item.id = ANY(deleted_item_ids)
          AND item.native_segment_id IS NOT NULL
    );
    deleted_video_ids := ARRAY(
        SELECT DISTINCT node.last_known_video_id
        FROM segment_studio_lineage_nodes AS node
        WHERE node.id = ANY(deleted_node_ids)
    );

    DELETE FROM segment_studio_lineage_issues AS issue
    WHERE issue.edge_id = ANY(removed_edge_ids)
       OR issue.lineage_node_id = ANY(deleted_node_ids);

    DELETE FROM segment_studio_incorrect_examples AS example
    WHERE example.item_id = ANY(deleted_item_ids);

    DELETE FROM segment_studio_history_sessions AS session
    WHERE session.video_id = ANY(deleted_video_ids);

    DELETE FROM segment_studio_derivation_edges AS edge
    WHERE edge.id = ANY(removed_edge_ids);

    DELETE FROM segment_studio_segment_provenance AS assertion
    WHERE assertion.lineage_node_id = ANY(deleted_node_ids);

    DELETE FROM segment_studio_lineage_nodes AS node
    WHERE node.id = ANY(deleted_node_ids);

    DELETE FROM segments AS segment
    WHERE segment."Id" = ANY(deleted_native_segment_ids);

    DELETE FROM segment_studio_items AS item
    WHERE item.id = ANY(deleted_item_ids);

    PERFORM segment_studio_retire_unsupported_inherited_provenance();

    RETURN OLD;
END
$function$
;
CREATE OR REPLACE FUNCTION segment_studio_expire_basic_history_receipt()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF OLD.receipt_id IS NOT NULL THEN
        UPDATE segment_studio_segment_operations
        SET kind = 'basic-native-history-receipt-expired',
            request_fingerprint = 'expired',
            item_id = NULL,
            source_native_segment_id = NULL,
            result_native_segment_id = NULL,
            result_payload = NULL,
            component_fingerprint = NULL
        WHERE operation_id = OLD.receipt_id
          AND kind = 'basic-native-history-receipt';
    END IF;
    RETURN OLD;
END;
$function$
;
CREATE OR REPLACE FUNCTION segment_studio_mark_deleted_item_missing()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE segment_studio_lineage_nodes
    SET item_id = NULL,
        state = 'missing',
        missing_since = COALESCE(missing_since, now()),
        updated_at = now()
    WHERE item_id = OLD.id;
    RETURN OLD;
END;
$function$
;
CREATE OR REPLACE FUNCTION segment_studio_prevent_native_derived_item()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.native_segment_id IS NOT NULL
       AND EXISTS (
           SELECT 1
           FROM segment_studio_lineage_nodes AS node
           JOIN segment_studio_derivation_edges AS edge
               ON edge.derived_node_id = node.id
           WHERE node.item_id = NEW.id
       )
    THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'A derived lineage item cannot be converted to a native Cove segment.';
    END IF;
    RETURN NEW;
END
$function$
;
CREATE OR REPLACE FUNCTION segment_studio_queue_export_blob_cleanup()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF OLD.image_blob_id IS NOT NULL THEN
        INSERT INTO segment_studio_blob_cleanup_outbox
            (blob_id, status, attempt_count, last_error, created_at, updated_at)
        VALUES
            (OLD.image_blob_id, 'pending', 0, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        ON CONFLICT (blob_id) DO UPDATE SET
            status = 'pending',
            attempt_count = 0,
            last_error = NULL,
            updated_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN OLD;
END;
$function$
;
CREATE OR REPLACE FUNCTION segment_studio_queue_native_bin_blob_cleanup()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF OLD.image_blob_id IS NOT NULL THEN
        INSERT INTO segment_studio_blob_cleanup_outbox
            (blob_id, status, attempt_count, last_error, created_at, updated_at)
        VALUES
            (OLD.image_blob_id, 'pending', 0, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        ON CONFLICT (blob_id) DO UPDATE
        SET status = 'pending', attempt_count = 0, last_error = NULL,
            updated_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN OLD;
END;
$function$
;
CREATE OR REPLACE FUNCTION segment_studio_queue_owned_blob_cleanup()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF OLD.native_segment_id IS NULL AND OLD.extension_image_blob_id IS NOT NULL THEN
        INSERT INTO segment_studio_blob_cleanup_outbox
            (blob_id, status, attempt_count, last_error, created_at, updated_at)
        VALUES
            (OLD.extension_image_blob_id, 'pending', 0, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        ON CONFLICT (blob_id) DO UPDATE
        SET status = 'pending', attempt_count = 0, last_error = NULL,
            updated_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN OLD;
END;
$function$
;
CREATE OR REPLACE FUNCTION segment_studio_require_owned_derived_endpoint()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM segment_studio_lineage_nodes AS node
        JOIN segment_studio_items AS item ON item.id = node.item_id
        WHERE node.id = NEW.derived_node_id
          AND item.native_segment_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'A native Cove segment cannot be a derived lineage endpoint.';
    END IF;
    RETURN NEW;
END
$function$
;
CREATE OR REPLACE FUNCTION segment_studio_retire_unsupported_inherited_provenance()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE segment_studio_segment_provenance AS inherited
    SET superseded_at = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP
    WHERE inherited.relation = 'inherited'
      AND inherited.superseded_at IS NULL
      AND NOT EXISTS (
          WITH RECURSIVE ancestors(node_id) AS (
              SELECT edge.source_node_id
              FROM segment_studio_derivation_edges AS edge
              WHERE edge.derived_node_id = inherited.lineage_node_id
              UNION
              SELECT edge.source_node_id
              FROM segment_studio_derivation_edges AS edge
              JOIN ancestors
                ON edge.derived_node_id = ancestors.node_id
          )
          SELECT 1
          FROM ancestors
          JOIN segment_studio_segment_provenance AS origin
            ON origin.lineage_node_id = ancestors.node_id
          WHERE origin.relation = 'origin'
            AND origin.superseded_at IS NULL
            AND origin.source_id = inherited.source_id
            AND origin.activity_id IS NOT DISTINCT FROM inherited.activity_id
            AND origin.model_key IS NOT DISTINCT FROM inherited.model_key
            AND origin.model_identifier IS NOT DISTINCT FROM inherited.model_identifier
            AND origin.model_version IS NOT DISTINCT FROM inherited.model_version
      );
END
$function$
;

-- Triggers and foreign keys.
CREATE TRIGGER segment_studio_derivation_rules_delete_derivations BEFORE DELETE ON segment_studio_derivation_rules FOR EACH ROW EXECUTE FUNCTION segment_studio_delete_rule_derivations();


--
-- Name: segment_studio_history_actions segment_studio_history_action_expire_receipt; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER segment_studio_history_action_expire_receipt AFTER DELETE ON segment_studio_history_actions FOR EACH ROW EXECUTE FUNCTION segment_studio_expire_basic_history_receipt();


--
-- Name: segment_studio_items segment_studio_items_mark_lineage_missing; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER segment_studio_items_mark_lineage_missing BEFORE DELETE ON segment_studio_items FOR EACH ROW EXECUTE FUNCTION segment_studio_mark_deleted_item_missing();


--
-- Name: segment_studio_items segment_studio_items_queue_blob_cleanup; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER segment_studio_items_queue_blob_cleanup BEFORE DELETE ON segment_studio_items FOR EACH ROW EXECUTE FUNCTION segment_studio_queue_owned_blob_cleanup();


--
-- Name: segment_studio_native_recycle_bin segment_studio_native_bin_queue_blob_cleanup; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER segment_studio_native_bin_queue_blob_cleanup BEFORE DELETE ON segment_studio_native_recycle_bin FOR EACH ROW EXECUTE FUNCTION segment_studio_queue_native_bin_blob_cleanup();


--
-- Name: segment_studio_items segment_studio_prevent_native_derived_item; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER segment_studio_prevent_native_derived_item BEFORE UPDATE OF native_segment_id ON segment_studio_items FOR EACH ROW EXECUTE FUNCTION segment_studio_prevent_native_derived_item();


--
-- Name: segment_studio_derivation_edges segment_studio_require_owned_derived_endpoint; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER segment_studio_require_owned_derived_endpoint BEFORE INSERT OR UPDATE OF derived_node_id ON segment_studio_derivation_edges FOR EACH ROW EXECUTE FUNCTION segment_studio_require_owned_derived_endpoint();


--
-- Name: segment_studio_training_export_frames segment_studio_training_export_frames_queue_blob_cleanup; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER segment_studio_training_export_frames_queue_blob_cleanup AFTER DELETE ON segment_studio_training_export_frames FOR EACH ROW EXECUTE FUNCTION segment_studio_queue_export_blob_cleanup();


--
-- Name: segment_studio_training_export_items segment_studio_training_export_items_queue_blob_cleanup; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER segment_studio_training_export_items_queue_blob_cleanup AFTER DELETE ON segment_studio_training_export_items FOR EACH ROW EXECUTE FUNCTION segment_studio_queue_export_blob_cleanup();


--
-- Name: segment_studio_analysis_candidates FK_segment_studio_analysis_candidates_items_item_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_analysis_candidates
    ADD CONSTRAINT "FK_segment_studio_analysis_candidates_items_item_id" FOREIGN KEY (item_id) REFERENCES segment_studio_items(id) ON DELETE SET NULL;


--
-- Name: segment_studio_derivation_edges FK_segment_studio_derivation_edges_activity; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_edges
    ADD CONSTRAINT "FK_segment_studio_derivation_edges_activity" FOREIGN KEY (activity_id) REFERENCES segment_studio_provenance_activities(id) ON DELETE RESTRICT;


--
-- Name: segment_studio_derivation_edges FK_segment_studio_derivation_edges_derived_node; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_edges
    ADD CONSTRAINT "FK_segment_studio_derivation_edges_derived_node" FOREIGN KEY (derived_node_id) REFERENCES segment_studio_lineage_nodes(id) ON DELETE CASCADE;


--
-- Name: segment_studio_derivation_edges FK_segment_studio_derivation_edges_derived_tag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_edges
    ADD CONSTRAINT "FK_segment_studio_derivation_edges_derived_tag" FOREIGN KEY (derived_tag_id_at_creation) REFERENCES tags("Id") ON DELETE RESTRICT;


--
-- Name: segment_studio_derivation_edges FK_segment_studio_derivation_edges_rule; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_edges
    ADD CONSTRAINT "FK_segment_studio_derivation_edges_rule" FOREIGN KEY (rule_id) REFERENCES segment_studio_derivation_rules(id) ON DELETE RESTRICT;


--
-- Name: segment_studio_derivation_edges FK_segment_studio_derivation_edges_source_node; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_edges
    ADD CONSTRAINT "FK_segment_studio_derivation_edges_source_node" FOREIGN KEY (source_node_id) REFERENCES segment_studio_lineage_nodes(id) ON DELETE CASCADE;


--
-- Name: segment_studio_derivation_edges FK_segment_studio_derivation_edges_source_tag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_edges
    ADD CONSTRAINT "FK_segment_studio_derivation_edges_source_tag" FOREIGN KEY (source_tag_id_at_creation) REFERENCES tags("Id") ON DELETE RESTRICT;


--
-- Name: segment_studio_derivation_rules FK_segment_studio_derivation_rules_derived_tag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_rules
    ADD CONSTRAINT "FK_segment_studio_derivation_rules_derived_tag" FOREIGN KEY (derived_tag_id) REFERENCES tags("Id") ON DELETE RESTRICT;


--
-- Name: segment_studio_derivation_rules FK_segment_studio_derivation_rules_source_tag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_derivation_rules
    ADD CONSTRAINT "FK_segment_studio_derivation_rules_source_tag" FOREIGN KEY (source_tag_id) REFERENCES tags("Id") ON DELETE RESTRICT;


--
-- Name: segment_studio_history_actions FK_segment_studio_history_actions_sessions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_history_actions
    ADD CONSTRAINT "FK_segment_studio_history_actions_sessions" FOREIGN KEY (session_id) REFERENCES segment_studio_history_sessions(id) ON DELETE CASCADE;


--
-- Name: segment_studio_history_sessions FK_segment_studio_history_sessions_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_history_sessions
    ADD CONSTRAINT "FK_segment_studio_history_sessions_users" FOREIGN KEY (user_id) REFERENCES users("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_history_sessions FK_segment_studio_history_sessions_videos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_history_sessions
    ADD CONSTRAINT "FK_segment_studio_history_sessions_videos" FOREIGN KEY (video_id) REFERENCES videos("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_incorrect_examples FK_segment_studio_incorrect_examples_items; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_incorrect_examples
    ADD CONSTRAINT "FK_segment_studio_incorrect_examples_items" FOREIGN KEY (item_id) REFERENCES segment_studio_items(id) ON DELETE RESTRICT;


--
-- Name: segment_studio_incorrect_examples FK_segment_studio_incorrect_examples_native_bin; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_incorrect_examples
    ADD CONSTRAINT "FK_segment_studio_incorrect_examples_native_bin" FOREIGN KEY (native_bin_entry_id) REFERENCES segment_studio_native_recycle_bin(id) ON DELETE RESTRICT;


--
-- Name: segment_studio_incorrect_examples FK_segment_studio_incorrect_examples_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_incorrect_examples
    ADD CONSTRAINT "FK_segment_studio_incorrect_examples_users" FOREIGN KEY (created_by_user_id) REFERENCES users("Id") ON DELETE SET NULL;


--
-- Name: segment_studio_incorrect_examples FK_segment_studio_incorrect_examples_videos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_incorrect_examples
    ADD CONSTRAINT "FK_segment_studio_incorrect_examples_videos" FOREIGN KEY (video_id) REFERENCES videos("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_items FK_segment_studio_items_native_segments; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_items
    ADD CONSTRAINT "FK_segment_studio_items_native_segments" FOREIGN KEY (native_segment_id) REFERENCES segments("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_items FK_segment_studio_items_tags; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_items
    ADD CONSTRAINT "FK_segment_studio_items_tags" FOREIGN KEY (tag_id) REFERENCES tags("Id") ON DELETE RESTRICT;


--
-- Name: segment_studio_items FK_segment_studio_items_videos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_items
    ADD CONSTRAINT "FK_segment_studio_items_videos" FOREIGN KEY (video_id) REFERENCES videos("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_lineage_issues FK_segment_studio_lineage_issues_edge; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_lineage_issues
    ADD CONSTRAINT "FK_segment_studio_lineage_issues_edge" FOREIGN KEY (edge_id) REFERENCES segment_studio_derivation_edges(id) ON DELETE SET NULL;


--
-- Name: segment_studio_lineage_issues FK_segment_studio_lineage_issues_node; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_lineage_issues
    ADD CONSTRAINT "FK_segment_studio_lineage_issues_node" FOREIGN KEY (lineage_node_id) REFERENCES segment_studio_lineage_nodes(id) ON DELETE SET NULL;


--
-- Name: segment_studio_lineage_nodes FK_segment_studio_lineage_nodes_item_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_lineage_nodes
    ADD CONSTRAINT "FK_segment_studio_lineage_nodes_item_id" FOREIGN KEY (item_id) REFERENCES segment_studio_items(id) ON DELETE RESTRICT;


--
-- Name: segment_studio_lineage_scan_runs FK_segment_studio_lineage_scan_runs_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_lineage_scan_runs
    ADD CONSTRAINT "FK_segment_studio_lineage_scan_runs_user" FOREIGN KEY (requested_by_user_id) REFERENCES users("Id") ON DELETE SET NULL;


--
-- Name: segment_studio_native_recycle_bin FK_segment_studio_native_bin_tags; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_native_recycle_bin
    ADD CONSTRAINT "FK_segment_studio_native_bin_tags" FOREIGN KEY (tag_id) REFERENCES tags("Id") ON DELETE RESTRICT;


--
-- Name: segment_studio_native_recycle_bin FK_segment_studio_native_bin_videos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_native_recycle_bin
    ADD CONSTRAINT "FK_segment_studio_native_bin_videos" FOREIGN KEY (video_id) REFERENCES videos("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_provenance_activities FK_segment_studio_provenance_activities_source_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_provenance_activities
    ADD CONSTRAINT "FK_segment_studio_provenance_activities_source_id" FOREIGN KEY (source_id) REFERENCES segment_studio_sources(id) ON DELETE RESTRICT;


--
-- Name: segment_studio_segment_group_tags FK_segment_studio_segment_group_tags_groups; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_group_tags
    ADD CONSTRAINT "FK_segment_studio_segment_group_tags_groups" FOREIGN KEY (segment_group_id) REFERENCES segment_studio_segment_groups(id) ON DELETE CASCADE;


--
-- Name: segment_studio_segment_group_tags FK_segment_studio_segment_group_tags_tags; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_group_tags
    ADD CONSTRAINT "FK_segment_studio_segment_group_tags_tags" FOREIGN KEY (tag_id) REFERENCES tags("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_segment_operations FK_segment_studio_segment_operations_items; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_operations
    ADD CONSTRAINT "FK_segment_studio_segment_operations_items" FOREIGN KEY (item_id) REFERENCES segment_studio_items(id) ON DELETE SET NULL;


--
-- Name: segment_studio_segment_provenance FK_segment_studio_segment_provenance_activity_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_provenance
    ADD CONSTRAINT "FK_segment_studio_segment_provenance_activity_id" FOREIGN KEY (activity_id) REFERENCES segment_studio_provenance_activities(id) ON DELETE RESTRICT;


--
-- Name: segment_studio_segment_provenance FK_segment_studio_segment_provenance_node_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_provenance
    ADD CONSTRAINT "FK_segment_studio_segment_provenance_node_id" FOREIGN KEY (lineage_node_id) REFERENCES segment_studio_lineage_nodes(id) ON DELETE CASCADE;


--
-- Name: segment_studio_segment_provenance FK_segment_studio_segment_provenance_source_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_provenance
    ADD CONSTRAINT "FK_segment_studio_segment_provenance_source_id" FOREIGN KEY (source_id) REFERENCES segment_studio_sources(id) ON DELETE RESTRICT;


--
-- Name: segment_studio_segment_slots FK_segment_studio_segment_slots_definitions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_slots
    ADD CONSTRAINT "FK_segment_studio_segment_slots_definitions" FOREIGN KEY (slot_definition_id) REFERENCES segment_studio_slot_definitions(id) ON DELETE CASCADE;


--
-- Name: segment_studio_segment_slots FK_segment_studio_segment_slots_items; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_slots
    ADD CONSTRAINT "FK_segment_studio_segment_slots_items" FOREIGN KEY (item_id) REFERENCES segment_studio_items(id) ON DELETE CASCADE;


--
-- Name: segment_studio_segment_slots FK_segment_studio_segment_slots_performers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_segment_slots
    ADD CONSTRAINT "FK_segment_studio_segment_slots_performers" FOREIGN KEY (performer_id) REFERENCES performers("Id") ON DELETE RESTRICT;


--
-- Name: segment_studio_shot_boundaries FK_segment_studio_shot_boundaries_videos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_shot_boundaries
    ADD CONSTRAINT "FK_segment_studio_shot_boundaries_videos" FOREIGN KEY (video_id) REFERENCES videos("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_shot_boundary_operations FK_segment_studio_shot_boundary_operations_videos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_shot_boundary_operations
    ADD CONSTRAINT "FK_segment_studio_shot_boundary_operations_videos" FOREIGN KEY (video_id) REFERENCES videos("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_slot_definition_gender_hints FK_segment_studio_slot_definition_gender_hints_definitions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_slot_definition_gender_hints
    ADD CONSTRAINT "FK_segment_studio_slot_definition_gender_hints_definitions" FOREIGN KEY (slot_definition_id) REFERENCES segment_studio_slot_definitions(id) ON DELETE CASCADE;


--
-- Name: segment_studio_slot_definition_sets FK_segment_studio_slot_definition_sets_tags; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_slot_definition_sets
    ADD CONSTRAINT "FK_segment_studio_slot_definition_sets_tags" FOREIGN KEY (tag_id) REFERENCES tags("Id") ON DELETE RESTRICT;


--
-- Name: segment_studio_slot_definitions FK_segment_studio_slot_definitions_sets; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_slot_definitions
    ADD CONSTRAINT "FK_segment_studio_slot_definitions_sets" FOREIGN KEY (slot_definition_set_id) REFERENCES segment_studio_slot_definition_sets(id) ON DELETE CASCADE;


--
-- Name: segment_studio_training_export_examples FK_segment_studio_training_export_examples_export; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_export_examples
    ADD CONSTRAINT "FK_segment_studio_training_export_examples_export" FOREIGN KEY (export_id) REFERENCES segment_studio_training_exports(id) ON DELETE CASCADE;


--
-- Name: segment_studio_training_export_frames FK_segment_studio_training_export_frames_example; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_export_frames
    ADD CONSTRAINT "FK_segment_studio_training_export_frames_example" FOREIGN KEY (export_example_id) REFERENCES segment_studio_training_export_examples(id) ON DELETE CASCADE;


--
-- Name: segment_studio_training_export_items FK_segment_studio_training_export_items_exports; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_export_items
    ADD CONSTRAINT "FK_segment_studio_training_export_items_exports" FOREIGN KEY (export_id) REFERENCES segment_studio_training_exports(id) ON DELETE CASCADE;


--
-- Name: segment_studio_training_exports FK_segment_studio_training_exports_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_exports
    ADD CONSTRAINT "FK_segment_studio_training_exports_users" FOREIGN KEY (requested_by_user_id) REFERENCES users("Id") ON DELETE SET NULL;


--
-- Name: segment_studio_training_exports FK_segment_studio_training_exports_videos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_training_exports
    ADD CONSTRAINT "FK_segment_studio_training_exports_videos" FOREIGN KEY (video_id) REFERENCES videos("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_user_preferences FK_segment_studio_user_preferences_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_user_preferences
    ADD CONSTRAINT "FK_segment_studio_user_preferences_users_user_id" FOREIGN KEY (user_id) REFERENCES users("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_analysis_candidates segment_studio_analysis_candidates_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_analysis_candidates
    ADD CONSTRAINT segment_studio_analysis_candidates_run_id_fkey FOREIGN KEY (run_id) REFERENCES segment_studio_analysis_runs(id) ON DELETE CASCADE;


--
-- Name: segment_studio_analysis_candidates segment_studio_analysis_candidates_video_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_analysis_candidates
    ADD CONSTRAINT segment_studio_analysis_candidates_video_id_fkey FOREIGN KEY (video_id) REFERENCES videos("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_analysis_runs segment_studio_analysis_runs_video_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_analysis_runs
    ADD CONSTRAINT segment_studio_analysis_runs_video_file_id_fkey FOREIGN KEY (video_file_id) REFERENCES files("Id") ON DELETE CASCADE;


--
-- Name: segment_studio_analysis_runs segment_studio_analysis_runs_video_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY segment_studio_analysis_runs
    ADD CONSTRAINT segment_studio_analysis_runs_video_id_fkey FOREIGN KEY (video_id) REFERENCES videos("Id") ON DELETE CASCADE;


--

-- Built-in provenance sources and clean-install rollout state.
INSERT INTO segment_studio_sources
    (key, display_name, category, provider, metadata, created_at, updated_at)
VALUES
    ('user', 'User', 'manual', 'Cove', '{}'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stash-marker-studio:manual', 'Stash Marker Studio Manual', 'manual', 'Stash Marker Studio', '{}'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stash-marker-studio:skier-ai', 'Skier AI via Stash Marker Studio', 'ai', 'Stash Marker Studio', '{}'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tpdb', 'The Porn Database', 'external', 'TPDB', '{}'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ext:ai.tagging', 'Cove AI Tagging', 'ai', 'Cove', '{}'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO segment_studio_installation_state
    (id, requires_legacy_normalization, lineage_rollout_paused, updated_at)
VALUES (1, FALSE, FALSE, CURRENT_TIMESTAMP);
