using Cove.Plugins;
using Cove.Sdk;

namespace SegmentStudio;

internal static class SegmentStudioKeyboardActions
{
    private static readonly UIKeyboardActionScope[] EditorScope =
        [new("local", Page: "segment-studio")];

    public static void AddTo(UIManifestBuilder builder)
    {
        builder
            .AddKeyboardAction("video.playPause", "Play or pause", ["Space", "k"], EditorScope, group: "Playback", order: 100)
            .AddKeyboardAction("video.seekSmallBackward", "Seek backward by the small interval", ["j"], EditorScope, group: "Playback", order: 101, repeatable: true)
            .AddKeyboardAction("video.seekSmallForward", "Seek forward by the small interval", ["l"], EditorScope, group: "Playback", order: 102, repeatable: true)
            .AddKeyboardAction("video.seekMediumBackward", "Seek backward by the medium interval", [], EditorScope, group: "Playback", order: 103, repeatable: true)
            .AddKeyboardAction("video.seekMediumForward", "Seek forward by the medium interval", [], EditorScope, group: "Playback", order: 104, repeatable: true)
            .AddKeyboardAction("video.seekLongBackward", "Seek backward by the long interval", ["Ctrl+Shift+j"], EditorScope, group: "Playback", order: 105, repeatable: true)
            .AddKeyboardAction("video.seekLongForward", "Seek forward by the long interval", ["Ctrl+Shift+l"], EditorScope, group: "Playback", order: 106, repeatable: true)
            .AddKeyboardAction("video.playSelected", "Play from the selected segment", ["Enter"], EditorScope, group: "Playback", order: 107)
            .AddKeyboardAction("video.playPreviousSegment", "Select and play the previous segment in this swimlane", ["Shift+j"], EditorScope, group: "Playback", order: 108)
            .AddKeyboardAction("video.playNextSegment", "Select and play the next segment in this swimlane", ["Shift+l"], EditorScope, group: "Playback", order: 109)
            .AddKeyboardAction("video.seekPercent10", "Seek to 10% of the video", ["1"], EditorScope, group: "Playback", order: 110, repeatable: true)
            .AddKeyboardAction("video.seekPercent20", "Seek to 20% of the video", ["2"], EditorScope, group: "Playback", order: 111, repeatable: true)
            .AddKeyboardAction("video.seekPercent30", "Seek to 30% of the video", ["3"], EditorScope, group: "Playback", order: 112, repeatable: true)
            .AddKeyboardAction("video.seekPercent40", "Seek to 40% of the video", ["4"], EditorScope, group: "Playback", order: 113, repeatable: true)
            .AddKeyboardAction("video.seekPercent50", "Seek to 50% of the video", ["5"], EditorScope, group: "Playback", order: 114, repeatable: true)
            .AddKeyboardAction("video.seekPercent60", "Seek to 60% of the video", ["6"], EditorScope, group: "Playback", order: 115, repeatable: true)
            .AddKeyboardAction("video.seekPercent70", "Seek to 70% of the video", ["7"], EditorScope, group: "Playback", order: 116, repeatable: true)
            .AddKeyboardAction("video.seekPercent80", "Seek to 80% of the video", ["8"], EditorScope, group: "Playback", order: 117, repeatable: true)
            .AddKeyboardAction("video.seekPercent90", "Seek to 90% of the video", ["9"], EditorScope, group: "Playback", order: 118, repeatable: true)
            .AddKeyboardAction("video.jumpToSegmentStart", "Jump to the selected segment start", ["i"], EditorScope, group: "Playback", order: 119)
            .AddKeyboardAction("video.jumpToVideoStart", "Jump to the video start", ["Shift+i"], EditorScope, group: "Playback", order: 120)
            .AddKeyboardAction("video.jumpToSegmentEnd", "Jump to the selected segment end", ["o"], EditorScope, group: "Playback", order: 121)
            .AddKeyboardAction("video.jumpToVideoEnd", "Jump to the video end", ["Shift+o"], EditorScope, group: "Playback", order: 122)
            .AddKeyboardAction("video.frameSmallBackward", "Step backward by the small frame count", [","], EditorScope, group: "Playback", order: 123, repeatable: true)
            .AddKeyboardAction("video.frameSmallForward", "Step forward by the small frame count", ["."], EditorScope, group: "Playback", order: 124, repeatable: true)
            .AddKeyboardAction("video.frameMediumBackward", "Step backward by the medium frame count", ["Shift+,", ";"], EditorScope, group: "Playback", order: 125, repeatable: true)
            .AddKeyboardAction("video.frameMediumForward", "Step forward by the medium frame count", ["Shift+.", ":"], EditorScope, group: "Playback", order: 126, repeatable: true)
            .AddKeyboardAction("video.frameLongBackward", "Step backward by the long frame count", ["Ctrl+;"], EditorScope, group: "Playback", order: 127, repeatable: true)
            .AddKeyboardAction("video.frameLongForward", "Step forward by the long frame count", ["Ctrl+:"], EditorScope, group: "Playback", order: 128, repeatable: true)
            .AddKeyboardAction("navigation.swimlaneUp", "Select nearest segment in the swimlane above", ["ArrowUp"], EditorScope, group: "Selection", order: 129, repeatable: true)
            .AddKeyboardAction("navigation.swimlaneDown", "Select nearest segment in the swimlane below", ["ArrowDown"], EditorScope, group: "Selection", order: 130, repeatable: true)
            .AddKeyboardAction("navigation.segmentGroupUp", "Select the swimlane group above", ["Shift+ArrowUp"], EditorScope, group: "Selection", order: 131)
            .AddKeyboardAction("navigation.segmentGroupDown", "Select the swimlane group below", ["Shift+ArrowDown"], EditorScope, group: "Selection", order: 132)
            .AddKeyboardAction("navigation.swimlaneLeft", "Select previous segment in this swimlane", ["ArrowLeft"], EditorScope, group: "Selection", order: 133, repeatable: true)
            .AddKeyboardAction("navigation.swimlaneRight", "Select next segment in this swimlane", ["ArrowRight"], EditorScope, group: "Selection", order: 134, repeatable: true)
            .AddKeyboardAction("navigation.extendSwimlaneLeft", "Extend selection to the previous segment in this swimlane", ["Shift+ArrowLeft"], EditorScope, group: "Selection", order: 135)
            .AddKeyboardAction("navigation.extendSwimlaneRight", "Extend selection to the next segment in this swimlane", ["Shift+ArrowRight"], EditorScope, group: "Selection", order: 136)
            .AddKeyboardAction("navigation.previousAtPlayhead", "Select previous segment at the playhead", ["["], EditorScope, group: "Selection", order: 137)
            .AddKeyboardAction("navigation.nextAtPlayhead", "Select next segment at the playhead", ["]"], EditorScope, group: "Selection", order: 138)
            .AddKeyboardAction("navigation.nearestInCurrentSwimlane", "Select the segment nearest the playhead in this swimlane", ["p"], EditorScope, group: "Selection", order: 139)
            .AddKeyboardAction("navigation.previousUnreviewedInSwimlane", "Select previous unreviewed segment in this swimlane", ["n"], EditorScope, group: "Selection", order: 140)
            .AddKeyboardAction("navigation.previousUnreviewedGlobal", "Select previous unreviewed segment across swimlanes", ["Shift+n"], EditorScope, group: "Selection", order: 141)
            .AddKeyboardAction("navigation.nextUnreviewedInSwimlane", "Select next unreviewed segment in this swimlane", ["m"], EditorScope, group: "Selection", order: 142)
            .AddKeyboardAction("navigation.nextUnreviewedGlobal", "Select next unreviewed segment across swimlanes", ["Shift+m"], EditorScope, group: "Selection", order: 143)
            .AddKeyboardAction("navigation.nextTouchingPlayhead", "Select next segment near the playhead", ["Tab"], EditorScope, group: "Selection", order: 144)
            .AddKeyboardAction("navigation.previousTouchingPlayhead", "Select previous segment near the playhead", ["Shift+Tab"], EditorScope, group: "Selection", order: 145)
            .AddKeyboardAction("navigation.quickSearch", "Quick-search visible segments", ["f"], EditorScope, group: "Selection", order: 146)
            .AddKeyboardAction("navigation.previousShot", "Jump to previous shot", ["y"], EditorScope, group: "Shots", order: 147)
            .AddKeyboardAction("navigation.nextShot", "Jump to next shot", ["u"], EditorScope, group: "Shots", order: 148)
            .AddKeyboardAction("shot.split", "Add or split a shot boundary at the playhead", ["Shift+a", "v"], EditorScope, group: "Shots", order: 149)
            .AddKeyboardAction("shot.merge", "Remove the shot boundary at the playhead and merge adjacent shots", ["Shift+v"], EditorScope, group: "Shots", order: 150)
            .AddKeyboardAction("markerGroup.toggleCollapse", "Collapse or expand the selected segment group", ["b"], EditorScope, group: "Segment groups", order: 151)
            .AddKeyboardAction("markerGroup.toggleAll", "Collapse or expand all segment groups", ["Shift+b"], EditorScope, group: "Segment groups", order: 152)
            .AddKeyboardAction("marker.create", "Create segment at the playhead", ["a"], EditorScope, group: "Editing", order: 153)
            .AddKeyboardAction("marker.duplicate", "Duplicate selected segment in place", ["d"], EditorScope, group: "Editing", order: 154)
            .AddKeyboardAction("marker.duplicateAtPlayhead", "Duplicate selected segment at the playhead", ["Shift+d"], EditorScope, group: "Editing", order: 155)
            .AddKeyboardAction("marker.split", "Split selected segment at the playhead", ["s"], EditorScope, group: "Editing", order: 156)
            .AddKeyboardAction("marker.editTag", "Edit the selected segment tag", ["q"], EditorScope, group: "Editing", order: 157)
            .AddKeyboardAction("marker.setStart", "Set selected segment start to the playhead", ["w"], EditorScope, group: "Editing", order: 158)
            .AddKeyboardAction("marker.setEnd", "Set selected segment end to the playhead", ["e"], EditorScope, group: "Editing", order: 159)
            .AddKeyboardAction("marker.copyTiming", "Copy selected segment timing", ["t"], EditorScope, group: "Editing", order: 160)
            .AddKeyboardAction("marker.pasteTiming", "Paste copied timing onto the selected segment", ["Shift+t"], EditorScope, group: "Editing", order: 161)
            .AddKeyboardAction("marker.mergeSelection", "Merge selected segments in one swimlane", ["r"], EditorScope, group: "Editing", order: 162)
            .AddKeyboardAction("marker.moveToBin", "Move selected segments to the recycling bin", ["x"], EditorScope, group: "Editing", order: 163)
            .AddKeyboardAction("system.emptyBin", "Empty the recycling bin", ["Shift+x"], EditorScope, group: "Editing", order: 164)
            .AddKeyboardAction("marker.toggleIncorrectExample", "Collect selected eligible AI segments as incorrect examples", ["c"], EditorScope, group: "AI feedback", order: 165)
            .AddKeyboardAction("marker.openIncorrectExamples", "Manage incorrect examples and download an AI Feedback ZIP", ["Shift+c"], EditorScope, group: "AI feedback", order: 166)
            .AddKeyboardAction("marker.assignSlots", "Assign performers to segment slots", ["g"], EditorScope, group: "Editing", order: 167)
            .AddKeyboardAction("navigation.centerPlayhead", "Center timeline on playhead", ["h"], EditorScope, group: "Timeline", order: 168)
            .AddKeyboardAction("navigation.zoomIn", "Zoom in", ["+", "="], EditorScope, group: "Timeline", order: 169, repeatable: true)
            .AddKeyboardAction("navigation.zoomOut", "Zoom out", ["-", "_"], EditorScope, group: "Timeline", order: 170, repeatable: true)
            .AddKeyboardAction("navigation.resetZoom", "Fit timeline", ["0"], EditorScope, group: "Timeline", order: 171)
            .AddKeyboardAction("layout.growSwimlanes", "Give swimlanes more height", ["Mod+ArrowUp"], EditorScope, group: "Timeline", order: 172)
            .AddKeyboardAction("layout.shrinkSwimlanes", "Give swimlanes less height", ["Mod+ArrowDown"], EditorScope, group: "Timeline", order: 173)
            .AddKeyboardAction("marker.confirm", "Approve or unapprove segment", ["z"], EditorScope, group: "Review", order: 174)
            .AddKeyboardAction("system.publishApproved", "Preview approved draft publishing", ["Shift+z"], EditorScope, group: "Review", order: 175)
            .AddKeyboardAction("marker.reject", "Reject or unreject segment", ["x"], EditorScope, group: "Review", order: 176)
            .AddKeyboardAction("system.deleteRejected", "Delete all rejected segments", ["Shift+x"], EditorScope, group: "Review", order: 177);
    }
}
