<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AuthMiddleware</AssemblyName>
    <RootNamespace>AuthMiddleware</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0" />
  </ItemGroup>

</Project>
