-- Archived pre-release workspace-to-stable-item operator transition.
-- This is not part of the Segment Studio 1.0 public migration chain.
CREATE TABLE segment_studio_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    native_segment_id INTEGER NULL,
    review_state VARCHAR(32) NULL,
    representation_schema_version INTEGER NOT NULL DEFAULT 1,
    video_id INTEGER NULL,
    start_sec DOUBLE PRECISION NULL,
    end_sec DOUBLE PRECISION NULL,
    tag_id INTEGER NULL,
    kind TEXT NULL,
    ref_id BIGINT NULL,
    payload JSONB NULL,
    source_key TEXT NULL,
    source_run_id TEXT NULL,
    confidence REAL NULL,
    title TEXT NULL,
    color_hint TEXT NULL,
    extension_image_blob_id TEXT NULL,
    revision BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_segment_studio_items_native_segments"
        FOREIGN KEY (native_segment_id) REFERENCES segments ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_segment_studio_items_videos"
        FOREIGN KEY (video_id) REFERENCES videos ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_segment_studio_items_tags"
        FOREIGN KEY (tag_id) REFERENCES tags ("Id") ON DELETE RESTRICT,
    CONSTRAINT "CK_segment_studio_items_schema_version"
        CHECK (representation_schema_version > 0),
    CONSTRAINT "CK_segment_studio_items_revision"
        CHECK (revision >= 0),
    CONSTRAINT "CK_segment_studio_items_representation"
        CHECK (
            (native_segment_id IS NOT NULL
                AND review_state IS NULL
                AND video_id IS NULL
                AND start_sec IS NULL
                AND end_sec IS NULL
                AND tag_id IS NULL
                AND kind IS NULL
                AND ref_id IS NULL
                AND payload IS NULL
                AND source_key IS NULL
                AND source_run_id IS NULL
                AND confidence IS NULL
                AND title IS NULL
                AND color_hint IS NULL
                AND extension_image_blob_id IS NULL)
            OR
            (native_segment_id IS NULL
                AND review_state IN ('unreviewed', 'approved', 'rejected')
                AND video_id IS NOT NULL
                AND start_sec IS NOT NULL
                AND tag_id IS NOT NULL
                AND kind IS NOT NULL
                AND source_key IS NOT NULL)
        )
);

CREATE UNIQUE INDEX "IX_segment_studio_items_native_segment"
    ON segment_studio_items (native_segment_id);
CREATE INDEX "IX_segment_studio_items_owned_video_state_start"
    ON segment_studio_items (video_id, review_state, start_sec, id)
    WHERE native_segment_id IS NULL;
CREATE INDEX "IX_segment_studio_items_owned_tag_state"
    ON segment_studio_items (tag_id, review_state, video_id, start_sec, id)
    WHERE native_segment_id IS NULL;
CREATE UNIQUE INDEX "IX_segment_studio_items_owned_blob"
    ON segment_studio_items (extension_image_blob_id)
    WHERE extension_image_blob_id IS NOT NULL;

CREATE TABLE segment_studio_segment_operations (
    operation_id UUID PRIMARY KEY,
    kind VARCHAR(64) NOT NULL,
    actor_user_id INTEGER NULL,
    request_fingerprint TEXT NOT NULL,
    item_id BIGINT NULL,
    source_native_segment_id INTEGER NULL,
    result_native_segment_id INTEGER NULL,
    result_payload JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_segment_studio_segment_operations_items"
        FOREIGN KEY (item_id) REFERENCES segment_studio_items (id) ON DELETE SET NULL
);
CREATE INDEX "IX_segment_studio_segment_operations_created"
    ON segment_studio_segment_operations (created_at);

CREATE TABLE segment_studio_blob_cleanup_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blob_id TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_segment_studio_blob_cleanup_status"
        CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    CONSTRAINT "CK_segment_studio_blob_cleanup_attempt_count"
        CHECK (attempt_count >= 0),
    UNIQUE (blob_id)
);
CREATE INDEX "IX_segment_studio_blob_cleanup_status_created"
    ON segment_studio_blob_cleanup_outbox (status, created_at);

CREATE FUNCTION segment_studio_queue_owned_blob_cleanup()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    IF OLD.native_segment_id IS NULL AND OLD.extension_image_blob_id IS NOT NULL THEN
        INSERT INTO segment_studio_blob_cleanup_outbox
            (blob_id, status, attempt_count, last_error, created_at, updated_at)
        VALUES
            (OLD.extension_image_blob_id, 'pending', 0, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        ON CONFLICT (blob_id) DO UPDATE
        SET status = 'pending', attempt_count = 0, last_error = NULL,
            updated_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN OLD;
END;
$function$;

CREATE TRIGGER segment_studio_items_queue_blob_cleanup
    BEFORE DELETE ON segment_studio_items
    FOR EACH ROW
    EXECUTE FUNCTION segment_studio_queue_owned_blob_cleanup();

ALTER TABLE segment_studio_segment_slots
    ADD COLUMN item_id BIGINT NULL;

INSERT INTO segment_studio_items (native_segment_id)
SELECT DISTINCT segment_id
FROM segment_studio_segment_slots
ON CONFLICT (native_segment_id) DO NOTHING;

UPDATE segment_studio_segment_slots AS slot
SET item_id = item.id
FROM segment_studio_items AS item
WHERE item.native_segment_id = slot.segment_id;

DROP INDEX IF EXISTS "IX_segment_studio_segment_slots_definition";
DROP INDEX IF EXISTS "IX_segment_studio_segment_slots_performer";
DROP INDEX IF EXISTS "IX_segment_studio_segment_slots_definition_performer_segment";

ALTER TABLE segment_studio_segment_slots
    DROP CONSTRAINT segment_studio_segment_slots_pkey,
    DROP CONSTRAINT "FK_segment_studio_segment_slots_segments",
    ALTER COLUMN item_id SET NOT NULL,
    DROP COLUMN segment_id,
    ADD CONSTRAINT "PK_segment_studio_segment_slots"
        PRIMARY KEY (item_id, slot_definition_id),
    ADD CONSTRAINT "FK_segment_studio_segment_slots_items"
        FOREIGN KEY (item_id) REFERENCES segment_studio_items (id) ON DELETE CASCADE;

CREATE INDEX "IX_segment_studio_segment_slots_definition"
    ON segment_studio_segment_slots (slot_definition_id, item_id);
CREATE INDEX "IX_segment_studio_segment_slots_performer"
    ON segment_studio_segment_slots (performer_id, item_id);
CREATE INDEX "IX_segment_studio_segment_slots_definition_performer_item"
    ON segment_studio_segment_slots (slot_definition_id, performer_id, item_id);

CREATE VIEW segment_studio_item_compatibility AS
SELECT
    item.id AS item_id,
    segment."Id" AS native_segment_id,
    segment."HostId" AS video_id,
    segment."TagId" AS tag_id,
    segment."StartSec" AS start_sec,
    segment."EndSec" AS end_sec,
    CASE
        WHEN segment."Payload" -> 'segmentStudio' ->> 'reviewState' IN ('approved', 'rejected')
            THEN segment."Payload" -> 'segmentStudio' ->> 'reviewState'
        ELSE 'unreviewed'
    END AS legacy_review_state
FROM segments AS segment
LEFT JOIN segment_studio_items AS item ON item.native_segment_id = segment."Id"
WHERE segment."HostType" = 1
  AND segment."Kind" = 'tag'
  AND segment."TagId" IS NOT NULL;
