import type { SVGProps } from "react";

const Icon = (props: SVGProps<SVGSVGElement>) => <svg {...props} />;
export const AlertTriangle = Icon;
export const ArrowDown = Icon;
export const ArrowUp = Icon;
export const Check = Icon;
export const ChevronLeft = Icon;
export const ChevronRight = Icon;
export const Copy = Icon;
export const Download = Icon;
export const ExternalLink = Icon;
export const Film = Icon;
export const Headphones = Icon;
export const Grid3X3 = Icon;
export const Loader2 = Icon;
export const Mic = Icon;
export const LayoutGrid = Icon;
export const List = Icon;
export const Pencil = Icon;
export const Play = Icon;
export const Plus = Icon;
export const RotateCcw = Icon;
export const Save = Icon;
export const Search = Icon;
export const Tags = Icon;
export const Trash2 = Icon;
export const Undo2 = Icon;
export const Upload = Icon;
export const X = Icon;
export const ZoomIn = Icon;
export const ZoomOut = Icon;

export const GripVertical = Icon;
export const Ban = Icon;
export const ChevronDown = Icon;
export const MoreHorizontal = Icon;
export const Flag = Icon;
export const Layers = Icon;
export const Pin = Icon;
export const RectangleHorizontal = Icon;
export const RefreshCw = Icon;
export const SkipForward = Icon;
export const Tag = Icon;
export const Users = Icon;
